name: Build and Push Image

on: push  # Runs the action every time new commit is pushed to the branch

# on:
#    workflow_dispatch:  Creates a button to manually start the action. You can also make it to run on pull requests or any other condition.

env:
  DOCKER_REPO: your_dockerhub_container

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get short commit hash.  # Useful to separate different containers based on the commit number
        run: echo "SHORT_COMMIT=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Create secrets in github repo settings (Need an admin role or correct rights)
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Settings -> Secrets and variables -> Actions
      
      ### If you need to build multiple docker containers with different config files
      # - name: COPY in Dockerfile. 
      #   run: cp config_sandbox.ini config.ini
      #   working-directory: ${{ github.workspace }}

      - name: Build and push sandbox image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}-${{ env.SHORT_COMMIT }}